#!/bin/bash
python run_fivo.py \
  --mode=train \
  --logdir="output/fivo/synthetic_1_bs_4_1000it_10p" \
  --model=vrnn \
  --bound=fivo \
  --summarize_every=100 \
  --batch_size=4 \
  --num_samples=10 \
  --learning_rate=0.0001 \
  --dataset_path="data/synthetic_model_1" \
  --dataset_type="synthetic" \
  --latent_size=32
python run_fivo.py \
  --mode=eval \
  --logdir="output/fivo/synthetic_1_bs_4_1000it_10p" \
  --model=vrnn \
  --bound=fivo \
  --summarize_every=100 \
  --batch_size=4 \
  --num_samples=10 \
  --learning_rate=0.0001 \
  --dataset_path="data/synthetic_model_1" \
  --dataset_type="synthetic" \
  --latent_size=32 \
  --split test
python run_fivo.py \
  --mode=sample \
  --logdir="output/fivo/synthetic_1_bs_4_1000it_10p" \
  --model=vrnn \
  --bound=fivo \
  --summarize_every=100 \
  --batch_size=4 \
  --num_samples=10 \
  --learning_rate=0.0001 \
  --dataset_path="data/synthetic_model_1" \
  --dataset_type="synthetic" \
  --latent_size=32 \
  --split=test \
  --prefix_length=12 \
  --sample_length=12