#!/usr/bin/env bash
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
python run_fivo.py   --mode=train   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=False
python run_fivo.py   --mode=eval   --logdir="output/elbo/synthetic_1_bs_4_bs_4_10p"   --model=vrnn   --bound=elbo   --summarize_every=10   --batch_size=4   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split test --standardize=False
