#!/usr/bin/env bash
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
python run_fivo.py   --mode=train   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --standardize=True
python run_fivo.py   --mode=eval   --logdir="output/fivo/synthetic_1_bs_32_10p_standardize"   --model=vrnn   --bound=fivo   --summarize_every=10   --batch_size=32   --num_samples=10   --learning_rate=0.0001   --dataset_path="data/synthetic_model_1"   --dataset_type="synthetic"   --latent_size=32 --split=test --standardize=True
